import type { RouteStopItem } from "@/db/schema";

export interface SeedRoute {
  routeNumber: string;
  name: string;
  origin: string;
  destination: string;
  color: string;
  frequencyMinutes: number;
  totalDistanceKm: string;
  peakDemandScore: number;
  avgDelayMinutes: number;
  crowdingFrequencyPct: number;
  active: boolean;
  stops: RouteStopItem[];
}

export const INITIAL_ROUTES: SeedRoute[] = [
  {
    routeNumber: "R-101",
    name: "North Metro Express → Main Engineering Quad",
    origin: "North Gate Metro Plaza",
    destination: "STEM & Engineering Complex",
    color: "#4F46E5", // Electric Indigo
    frequencyMinutes: 10,
    totalDistanceKm: "11.8",
    peakDemandScore: 94,
    avgDelayMinutes: 2,
    crowdingFrequencyPct: 68,
    active: true,
    stops: [
      {
        id: "r101-s1",
        name: "North Gate Metro Plaza",
        code: "NGM-01",
        sequence: 1,
        etaOffsetMinutes: 0,
        x: 110,
        y: 125,
        landmark: "Metro Exit B & Bike Share Hub",
        waitingStudents: 34,
      },
      {
        id: "r101-s2",
        name: "University Residence Halls A-D",
        code: "URH-02",
        sequence: 2,
        etaOffsetMinutes: 5,
        x: 275,
        y: 165,
        landmark: "Freshman Commons Archway",
        waitingStudents: 28,
      },
      {
        id: "r101-s3",
        name: "Central Library & Student Union",
        code: "CLU-03",
        sequence: 3,
        etaOffsetMinutes: 11,
        x: 495,
        y: 255,
        landmark: "Clocktower Plaza Stop",
        waitingStudents: 41,
      },
      {
        id: "r101-s4",
        name: "Science & Bio-Tech Pavilion",
        code: "SBP-04",
        sequence: 4,
        etaOffsetMinutes: 16,
        x: 685,
        y: 230,
        landmark: "Solar Canopy West",
        waitingStudents: 19,
      },
      {
        id: "r101-s5",
        name: "STEM & Engineering Complex",
        code: "SEC-05",
        sequence: 5,
        etaOffsetMinutes: 21,
        x: 865,
        y: 190,
        landmark: "Robotics Foundry Main Bay",
        waitingStudents: 12,
      },
    ],
  },
  {
    routeNumber: "R-102",
    name: "South Hostel Loop → Academic Core",
    origin: "South Maple Student Village",
    destination: "Central Library & Student Union",
    color: "#06B6D4", // Transit Cyan
    frequencyMinutes: 12,
    totalDistanceKm: "9.4",
    peakDemandScore: 97,
    avgDelayMinutes: 7,
    crowdingFrequencyPct: 86,
    active: true,
    stops: [
      {
        id: "r102-s1",
        name: "South Maple Student Village",
        code: "SMV-01",
        sequence: 1,
        etaOffsetMinutes: 0,
        x: 135,
        y: 490,
        landmark: "South Dining Hall Turnaround",
        waitingStudents: 52,
      },
      {
        id: "r102-s2",
        name: "Oakridge Off-Campus Apartments",
        code: "OOA-02",
        sequence: 2,
        etaOffsetMinutes: 6,
        x: 315,
        y: 445,
        landmark: "Oakridge Crossing Shelter",
        waitingStudents: 39,
      },
      {
        id: "r102-s3",
        name: "Athletics & Aquatics Arena",
        code: "AAA-03",
        sequence: 3,
        etaOffsetMinutes: 12,
        x: 480,
        y: 380,
        landmark: "Gate 4 Stadium Concourse",
        waitingStudents: 22,
      },
      {
        id: "r102-s4",
        name: "Central Library & Student Union",
        code: "CLU-03",
        sequence: 4,
        etaOffsetMinutes: 18,
        x: 495,
        y: 255,
        landmark: "Clocktower Plaza Stop",
        waitingStudents: 41,
      },
      {
        id: "r102-s5",
        name: "Medical & Allied Health Wing",
        code: "MAH-05",
        sequence: 5,
        etaOffsetMinutes: 24,
        x: 690,
        y: 365,
        landmark: "Clinical Simulation Center",
        waitingStudents: 15,
      },
    ],
  },
  {
    routeNumber: "R-104",
    name: "West Downtown Rail Connector",
    origin: "Westside Intermodal Rail Station",
    destination: "Innovation Research Park",
    color: "#10B981", // Emerald
    frequencyMinutes: 15,
    totalDistanceKm: "15.2",
    peakDemandScore: 78,
    avgDelayMinutes: 4,
    crowdingFrequencyPct: 52,
    active: true,
    stops: [
      {
        id: "r104-s1",
        name: "Westside Intermodal Rail Station",
        code: "WIR-01",
        sequence: 1,
        etaOffsetMinutes: 0,
        x: 90,
        y: 310,
        landmark: "Bay 3 Regional Transit Terminal",
        waitingStudents: 29,
      },
      {
        id: "r104-s2",
        name: "Fine Arts & Design Conservatory",
        code: "FAD-02",
        sequence: 2,
        etaOffsetMinutes: 7,
        x: 290,
        y: 295,
        landmark: "Sculpture Garden East",
        waitingStudents: 18,
      },
      {
        id: "r104-s3",
        name: "Central Library & Student Union",
        code: "CLU-03",
        sequence: 3,
        etaOffsetMinutes: 13,
        x: 495,
        y: 255,
        landmark: "Clocktower Plaza Stop",
        waitingStudents: 41,
      },
      {
        id: "r104-s4",
        name: "School of Business & Law",
        code: "SBL-04",
        sequence: 4,
        etaOffsetMinutes: 19,
        x: 710,
        y: 120,
        landmark: "Founders Amphitheater",
        waitingStudents: 24,
      },
      {
        id: "r104-s5",
        name: "Innovation Research Park",
        code: "IRP-05",
        sequence: 5,
        etaOffsetMinutes: 26,
        x: 890,
        y: 340,
        landmark: "CleanTech Incubator Hub",
        waitingStudents: 14,
      },
    ],
  },
  {
    routeNumber: "R-108",
    name: "East Campus Perimeter Night & Lab Shuttle",
    origin: "Graduate Family Housing East",
    destination: "North Gate Metro Plaza",
    color: "#F59E0B", // Amber
    frequencyMinutes: 20,
    totalDistanceKm: "13.6",
    peakDemandScore: 71,
    avgDelayMinutes: 9,
    crowdingFrequencyPct: 44,
    active: true,
    stops: [
      {
        id: "r108-s1",
        name: "Graduate Family Housing East",
        code: "GFH-01",
        sequence: 1,
        etaOffsetMinutes: 0,
        x: 865,
        y: 485,
        landmark: "East Community Center",
        waitingStudents: 21,
      },
      {
        id: "r108-s2",
        name: "Medical & Allied Health Wing",
        code: "MAH-05",
        sequence: 2,
        etaOffsetMinutes: 6,
        x: 690,
        y: 365,
        landmark: "Clinical Simulation Center",
        waitingStudents: 15,
      },
      {
        id: "r108-s3",
        name: "Science & Bio-Tech Pavilion",
        code: "SBP-04",
        sequence: 3,
        etaOffsetMinutes: 12,
        x: 685,
        y: 230,
        landmark: "Solar Canopy West",
        waitingStudents: 19,
      },
      {
        id: "r108-s4",
        name: "University Residence Halls A-D",
        code: "URH-02",
        sequence: 4,
        etaOffsetMinutes: 19,
        x: 275,
        y: 165,
        landmark: "Freshman Commons Archway",
        waitingStudents: 28,
      },
      {
        id: "r108-s5",
        name: "North Gate Metro Plaza",
        code: "NGM-01",
        sequence: 5,
        etaOffsetMinutes: 25,
        x: 110,
        y: 125,
        landmark: "Metro Exit B & Bike Share Hub",
        waitingStudents: 34,
      },
    ],
  },
];

export const INITIAL_BUSES = [
  {
    busCode: "PS-01",
    plateNumber: "CA-UNIV-4018",
    routeNumber: "R-101",
    driverName: "Marcus Vance",
    driverPhone: "+1 (555) 234-8810",
    capacity: 50,
    occupancy: 31,
    status: "On Time",
    delayMinutes: 0,
    currentStopIndex: 1,
    currentLocation: "University Residence Halls A-D",
    nextStop: "Central Library & Student Union",
    etaMinutes: 3,
    speedKmh: 38,
    mapX: 365,
    mapY: 202,
    heading: "Eastbound → STEM Complex",
  },
  {
    busCode: "PS-02",
    plateNumber: "CA-UNIV-4022",
    routeNumber: "R-101",
    driverName: "Elena Rostova",
    driverPhone: "+1 (555) 234-8819",
    capacity: 50,
    occupancy: 22,
    status: "On Time",
    delayMinutes: 0,
    currentStopIndex: 3,
    currentLocation: "Science & Bio-Tech Pavilion",
    nextStop: "STEM & Engineering Complex",
    etaMinutes: 4,
    speedKmh: 41,
    mapX: 760,
    mapY: 212,
    heading: "Eastbound → STEM Complex",
  },
  {
    busCode: "PS-03",
    plateNumber: "CA-UNIV-5109",
    routeNumber: "R-102",
    driverName: "Darius Sterling",
    driverPhone: "+1 (555) 390-1142",
    capacity: 50,
    occupancy: 50,
    status: "Full",
    delayMinutes: 2,
    currentStopIndex: 1,
    currentLocation: "Oakridge Off-Campus Apartments",
    nextStop: "Athletics & Aquatics Arena",
    etaMinutes: 2,
    speedKmh: 31,
    mapX: 395,
    mapY: 412,
    heading: "Northbound → Academic Core",
  },
  {
    busCode: "PS-04",
    plateNumber: "CA-UNIV-5114",
    routeNumber: "R-102",
    driverName: "Priya Nair",
    driverPhone: "+1 (555) 390-1198",
    capacity: 50,
    occupancy: 46,
    status: "Delayed",
    delayMinutes: 9,
    currentStopIndex: 0,
    currentLocation: "South Maple Student Village",
    nextStop: "Oakridge Off-Campus Apartments",
    etaMinutes: 11,
    speedKmh: 18,
    mapX: 210,
    mapY: 470,
    heading: "Delayed at South Turnpike Crossing",
  },
  {
    busCode: "PS-05",
    plateNumber: "CA-UNIV-6201",
    routeNumber: "R-104",
    driverName: "Tomás Herrera",
    driverPhone: "+1 (555) 481-7730",
    capacity: 55,
    occupancy: 29,
    status: "On Time",
    delayMinutes: 0,
    currentStopIndex: 2,
    currentLocation: "Central Library & Student Union",
    nextStop: "School of Business & Law",
    etaMinutes: 5,
    speedKmh: 39,
    mapX: 590,
    mapY: 195,
    heading: "Northeast → Innovation Park",
  },
  {
    busCode: "PS-06",
    plateNumber: "CA-UNIV-7088",
    routeNumber: "R-108",
    driverName: "Hannah Lindqvist",
    driverPhone: "+1 (555) 892-3304",
    capacity: 45,
    occupancy: 39,
    status: "Delayed",
    delayMinutes: 7,
    currentStopIndex: 1,
    currentLocation: "Medical & Allied Health Wing",
    nextStop: "Science & Bio-Tech Pavilion",
    etaMinutes: 8,
    speedKmh: 22,
    mapX: 688,
    mapY: 305,
    heading: "Northbound → Metro Plaza",
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    type: "arriving_soon",
    title: "Bus PS-01 Arriving in 3 Mins",
    message:
      "Route R-101 (North Metro Express) is approaching Central Library & Student Union with 19 seats available.",
    routeNumber: "R-101",
    busCode: "PS-01",
    severity: "info",
    isRead: false,
  },
  {
    type: "crowded",
    title: "Bus PS-03 at 100% Capacity (Full)",
    message:
      "Bus PS-03 on Route R-102 has reached full capacity at Oakridge Off-Campus Apartments. Next shuttle PS-04 is following behind.",
    routeNumber: "R-102",
    busCode: "PS-03",
    severity: "critical",
    isRead: false,
  },
  {
    type: "delay",
    title: "9-Min Delay on Route R-102 (Bus PS-04)",
    message:
      "Heavy morning traffic near South Maple crossing has delayed Bus PS-04 by 9 minutes. Live ETA updated automatically.",
    routeNumber: "R-102",
    busCode: "PS-04",
    severity: "warning",
    isRead: false,
  },
  {
    type: "route_change",
    title: "Stop Bay Adjustment at Science Pavilion",
    message:
      "Due to solar canopy maintenance, Route R-101 and R-108 buses are boarding 40m west at Temporary Bay B today.",
    routeNumber: "R-101",
    busCode: "PS-02",
    severity: "info",
    isRead: true,
  },
];

export const INITIAL_ISSUES = [
  {
    studentName: "Aiden Chen",
    studentId: "STU-2026-8491",
    busCode: "PS-03",
    routeNumber: "R-102",
    stopName: "Oakridge Off-Campus Apartments",
    category: "Bus overcrowded",
    severity: "High",
    description:
      "More than 25 students were left waiting at Oakridge shelter at 8:15 AM because PS-03 was already 100% full from South Maple Village.",
    status: "Open",
    adminNote: "Dispatching reserve relief shuttle on R-102 corridor.",
  },
  {
    studentName: "Maya Patel",
    studentId: "STU-2026-3104",
    busCode: "PS-04",
    routeNumber: "R-102",
    stopName: "South Maple Student Village",
    category: "Bus delayed",
    severity: "Medium",
    description:
      "Bus PS-04 has been held at the South Maple intersection for nearly 10 minutes before morning lab exam.",
    status: "Investigating",
    adminNote: "Contacted driver Priya Nair; municipal signal timing issue reported.",
  },
  {
    studentName: "Lucas Meyer",
    studentId: "STU-2026-5520",
    busCode: "PS-06",
    routeNumber: "R-108",
    stopName: "Medical & Allied Health Wing",
    category: "Other transport issue",
    severity: "Low",
    description:
      "Digital route marquee on the front of PS-06 is flickering, making it hard to read in bright sunlight.",
    status: "Resolved",
    adminNote: "LED controller reset by fleet technician during turnaround.",
  },
];

export interface HourlyDemandPoint {
  hour: string;
  label: string;
  riders: number;
  capacity: number;
  avgDelayMins: number;
  overcrowdedBuses: number;
  period: "Morning Surge" | "Midday Class Shift" | "Evening Peak" | "Off-Peak";
}

export const HOURLY_ANALYTICS_DATA: HourlyDemandPoint[] = [
  { hour: "07:00", label: "7 AM", riders: 320, capacity: 450, avgDelayMins: 1, overcrowdedBuses: 0, period: "Off-Peak" },
  { hour: "08:00", label: "8 AM", riders: 890, capacity: 750, avgDelayMins: 8, overcrowdedBuses: 3, period: "Morning Surge" },
  { hour: "09:00", label: "9 AM", riders: 840, capacity: 750, avgDelayMins: 6, overcrowdedBuses: 2, period: "Morning Surge" },
  { hour: "10:00", label: "10 AM", riders: 510, capacity: 600, avgDelayMins: 2, overcrowdedBuses: 0, period: "Midday Class Shift" },
  { hour: "11:00", label: "11 AM", riders: 460, capacity: 600, avgDelayMins: 2, overcrowdedBuses: 0, period: "Midday Class Shift" },
  { hour: "12:00", label: "12 PM", riders: 620, capacity: 650, avgDelayMins: 4, overcrowdedBuses: 1, period: "Midday Class Shift" },
  { hour: "13:00", label: "1 PM", riders: 580, capacity: 650, avgDelayMins: 3, overcrowdedBuses: 1, period: "Midday Class Shift" },
  { hour: "14:00", label: "2 PM", riders: 490, capacity: 600, avgDelayMins: 2, overcrowdedBuses: 0, period: "Midday Class Shift" },
  { hour: "15:00", label: "3 PM", riders: 540, capacity: 650, avgDelayMins: 3, overcrowdedBuses: 0, period: "Midday Class Shift" },
  { hour: "16:00", label: "4 PM", riders: 780, capacity: 750, avgDelayMins: 6, overcrowdedBuses: 2, period: "Evening Peak" },
  { hour: "17:00", label: "5 PM", riders: 920, capacity: 750, avgDelayMins: 9, overcrowdedBuses: 3, period: "Evening Peak" },
  { hour: "18:00", label: "6 PM", riders: 690, capacity: 700, avgDelayMins: 5, overcrowdedBuses: 1, period: "Evening Peak" },
  { hour: "19:00", label: "7 PM", riders: 390, capacity: 500, avgDelayMins: 1, overcrowdedBuses: 0, period: "Off-Peak" },
  { hour: "20:00", label: "8 PM", riders: 260, capacity: 450, avgDelayMins: 1, overcrowdedBuses: 0, period: "Off-Peak" },
];
